# Site settings
title: Randy Leighton's Blog
email: randyleighton@yahoo.com
description: Technical Blogging around Ruby, Rails, and Javascript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://randyleighton.github.io" # the base hostname & protocol for your site
twitter_username: randyleighton
github_username:  randyleighton

# Build settings
markdown: kramdown
